describe('Form', () => {
  it('should validate all required fields', function () {
    cy.visit('/e2e-testing/example-form')
      .get('#first-step .next-btn').should('be.disabled')
      .get('#name').type('Claudio').blur()
      .get('#first-step .next-btn').should('be.disabled')
      .get('#surname').type('Cortese').blur()
      .get('#first-step .next-btn').should('not.be.disabled').click()
      .get('#phoneNumber').type('0810608213').blur()
      .get('#second-step .prev-btn').should('not.be.disabled')
      .get('#second-step .next-btn').should('be.disabled')
      .get('#email').type('claudio.cortese').blur()
      .get('#second-step .next-btn').should('be.disabled')
      .get('#email').clear().type('claudio.cortese@abstract-technology.com').blur()
      .get('#second-step .next-btn').should('not.be.disabled').click()
      .get('#third-step .prev-btn').should('not.be.disabled').click()
      .get('#phoneNumber').clear().blur()
      .get('#second-step .next-btn').should('not.be.disabled').click()
      .get('#taxCode').type('CRTCLD9718F39').blur()
      .get('#taxCode').clear().type('CRTCLD97A18F839M').blur()
      .get('#submit').click()
  })
})
