describe('Form', () => {
  it('should validate all required fields', function () {
    cy.visit('example-form')
    cy.get('#first-step .next-btn').should('be.disabled')
    cy.get('#name').type('Claudio').blur()
    cy.get('#first-step .next-btn').should('be.disabled')
    cy.get('#surname').type('Cortese').blur()
    cy.get('#first-step .next-btn').should('not.be.disabled').click()
    cy.get('#phoneNumber').type('0810608213').blur()
    cy.get('#second-step .prev-btn').should('not.be.disabled')
    cy.get('#second-step .next-btn').should('be.disabled')
    cy.get('#email').type('claudio.cortese').blur()
    cy.get('#second-step .next-btn').should('be.disabled')
    cy.get('#email').clear().type('claudio.cortese@abstract-technology.com').blur()
    cy.get('#second-step .next-btn').should('not.be.disabled').click()
    cy.get('#third-step .prev-btn').should('not.be.disabled').click()
    cy.get('#phoneNumber').clear().blur()
    cy.get('#second-step .next-btn').should('not.be.disabled').click()
    cy.get('#taxCode').type('CRTCLD9718F39').blur()
    cy.get('#taxCode').clear().type('CRTCLD97A18F839M').blur()
  })
})
